#!/usr/bin/env python3
"""helpdoc.py — packetized help for the current PythField GPT stack"""

# ============================================================================
# CORE TEXT
# ============================================================================

# [1:0] HELP_LINES_BEGIN
HELP_LINES = [
    'OPTERIUM HELP — RUNTIME + FIELD REFERENCE',
    '',
    'NAVIGATOR:',
    '  /help     → runtime contract, workflow, guaranteed names',
    '  /axioms   → what a number is here',
    '  /geom     → route cookbook, 2D/3D/atlas geometry',
    '  /gpt      → reasoning protocol for AI inside this field',
    '  /academy  → deeper system notes, recovered layers',
    '  /pyth     → verified current facts and invariants',
    '  /macros   → macro contract, persistence, trust protocol',
    '  /api      → live signatures — READ THIS FIRST',
    '  /opt_geom → OPT_G descent geometry',
    '  /doctor   → closure, verdict, tunnel, fingerprint',
    '',
    'SELF-DIAGNOSIS (run this first in any session):',
    '  api()   → prints all live objects with signatures',
    '            shows what is actually loaded right now',
    '            never guess — run api() when unsure',
    '',
    'WHAT THIS IS:',
    '  A geometric relational field, not a calculator.',
    '  Number = relational web {(x,y) | x*y = P}.',
    '  Pt(x,y) is a 2D address. P=xy, S=x+y, D=x-y.',
    '  Identity: P = (S² - D²) / 4.',
    '  3D is primary. 2D is the witness/face layer.',
    '',
    'WORKFLOW:',
    '  1. AI writes Python code.',
    '  2. User pastes into Code panel and presses RUN.',
    '  3. User sends Out / Err / Val back to AI.',
    '  Everything typed is PYTHON CODE, not chat.',
    '',
    'OUTPUT CONTRACT (verified in current executor):',
    '  print(...)             → Out (visible)',
    '  builtins.print(...)    → same as print, goes to Out',
    '  Last expression        → Val automatically',
    '  R(x)                   → publish to S.res, also returns x',
    '  In macros: print(...)  → also goes to Out',
    '',
    'STATE CONTRACT:',
    '  S.tmp   cleared each RUN',
    '  S.per   persists across RUNs in the same session',
    '  keep("name")  protect tmp name from clearing',
    '  lazy(name, gen, mx)  lazy cache',
    '  NEVER do: S = anything  (breaks the whole environment)',
    '',
    'RUNTIME PREPROCESSING:',
    '  Slash commands expanded before execution:',
    '    /help /axioms /geom /gpt /academy /pyth /macros /api /opt_geom /doctor',
    "  Macro sugar: 12M[name]34 → S.mac['name'](12,34)",
    '  Last expression rewritten into "_" → Val',
    '',
    'ALWAYS-AVAILABLE OBJECTS (from opterium_field.py):',
    '  2D field: Pt, Web, Sh, Tag, canon, field, web',
    '  2D routes: sd, ps, pd, ant, dia, get',
    '  3D field: Pt3, cube_field',
    '  Ternary address: Addr3, addr3, Axis',
    '  Rich 3D cell: CubeCell',
    '  Fractal 3×3×3: Cube27',
    '  9-cube atlas: field9, Tag3',
    '  E8 root lattice: e8gen, e8',
    '  Doctor health layer: doctor, HealthVector, DoctorVerdict, ReactionLevel',
    '  Exact geometry: CellBox, LineDNA',
    '  Universal division: universal_division',
    '  Relational graphs: Plafal, make_plafal',
    '  Facade: opterium, of',
    '  State / macros: S, keep, unkeep, lazy, lg, rs, info',
    '                   mac, unmac, macs, R, tm, ms',
    '',
    'OPTIONAL OBJECTS (when modules installed):',
    '  chat_proxy              LLM proxy',
    '  DebtNum, RatioRule, RepeatingRule, IrrationalRule  (pathnum.py)',
    '  sequence_packet, resonance_din, e8_seed_hint       (resonance_geom.py)',
    '  div_geom, ratio_geom, sqrt_geom                    (division_geom.py)',
    '',
    'QUICK EXAMPLES:',
    '  web(420).at(12)                   # Pt(12,35)',
    '  web(420).has(13)                  # False',
    '  web(144).on_diag()                # Pt(12,12)',
    '  web(97).edge_only()               # True (prime)',
    '  sd(47,-23)                        # Pt(12,35)',
    '  CubeCell(2,3,5).packet()          # full 3D cell',
    '  Cube27().doctor()["total_cells"]  # 27',
    '  Addr3.of(9,9,9).is_on_axis        # True',
    '  Axis.optg_path(1,2,3)             # [(1,2,3),(1,2,0),(1,1,1)]',
    '  field9.point_report(-5,2,-3)      # atlas report',
    '  e8gen.spectrum(0)                 # {-8:1,-4:56,0:126,4:56,8:1}',
    '  doctor.pt3_field3(9,9,9)["signature"]  # "CLOSED"',
    '  universal_division(420, 12)       # {"method":"web_witness","exact":True}',
    '',
    'PERFORMANCE RULE:',
    '  Prefer WITNESS queries to REVEAL.',
    '  WITNESS: web(P).at(d), web(P).has(d), sd(S,D), Pt.pos',
    '  REVEAL: pairs_u, pairs, divs, idx — cost O(sqrt(P))',
    '  huge P → witness only',
    '',
    'LOGGING DISCIPLINE:',
    '  Say briefly WHAT was tested, not only that it worked.',
    '  Prefer compact Val packets over noisy prose.',
    '',
    'FINAL WARNING:',
    '  Trust closures, witnesses, and independent route agreement.',
    '  Do not trust one vivid example more than the structure that closes around it.',
]
# [1:1] HELP_LINES_END

# [2:0] AXIOMS_LINES_BEGIN
AXIOMS_LINES = [
    'PYTHFIELD AXIOMS — what numbers ARE here',
    '',
    'A1. NUMBER = RELATIONAL WEB',
    '  A positive integer P is the full web of ordered pairs (x,y) such that x*y = P.',
    '  Example: 420 IS the web {(1,420),(2,210),(3,140),(4,105),(5,84),',
    '  (6,70),(7,60),(10,42),(12,35),(14,30),(15,28),(20,21)}.',
    '',
    'A2. ATOM = ADDRESS: Pt(x,y)',
    '  Pt(x,y) is the minimal 2D address. From it we read:',
    '    x, y',
    '    P = x*y',
    '    S = x+y',
    '    D = x-y',
    '    pos = sign(D)',
    '  Central identity: P = (S^2 - D^2) / 4.',
    '',
    'A3. THREE ROADS CROSS EVERY CELL',
    '  web(P): hyperbola xy=P',
    '  ant(S): anti-diagonal x+y=S',
    '  dia(D): diagonal x-y=D',
    '  Any two roads determine the cell:',
    '    sd(S,D) -> unique Pt or None',
    '    ps(P,S) -> 0 or 2 points',
    '    pd(P,D) -> 0 or 1 point',
    '',
    'A4. OPERATIONS = NAVIGATION',
    '  Addition:      Pt(a,b).S',
    '  Subtraction:   Pt(a,b).D',
    '  Comparison:    Pt(a,b).pos',
    '  Multiplication:Pt(a,b).P',
    '  Division:      web(P).at(d)',
    '  Square root:   web(n).on_diag()',
    '  Prime witness: web(n).edge_only()',
    '  These are route-reads, not schoolbook digit procedures.',
    '',
    'A5. SAME SHADOW ≠ SAME ADDRESS',
    '  Pt(4,3) and Pt(3,4) share P=12 and S=7,',
    '  but are different addresses (D=+1 vs D=-1).',
    '',
    'A6. COMPARISON IS FREE IN D',
    '  sign(D) already tells which side is larger.',
    '  No extra subtraction ritual is needed.',
    '',
    'A7. SCALE AND PATTERN ARE SEPARATE',
    '  gcd layer:',
    '    g = gcd(x,y)',
    '    prim = Pt(x/g,y/g)',
    '    prim.sc(g) = original point',
    '  decimal / debt layer:',
    '    Sh(m,e) = m * 10^e exactly',
    '    mantissa stores pattern, debt stores cursor/scale.',
    '',
    'A8. ZERO IS THE CENTER OF CENTERS',
    '  Zero is the vacuum and symmetry medium of the field.',
    '  It is not mere absence; it is absolute symmetry.',
    '',
    'A9. DECIMAL POINT IS A CURSOR, NOT THE NUMBER',
    '  Moving the cursor changes scale, not the underlying pattern.',
    '',
    'A10. 3D IS PRIMARY IN THE CURRENT STACK',
    '  Pt3(x,y,z) carries:',
    '    V = x*y*z',
    '    S_lin = x+y+z',
    '    C_plan = xy+xz+yz',
    '    D_body = max(|coords|) - min(|coords|)',
    '  2D survives as built-in face/slice layer (slice_xy, slice_xz, slice_yz).',
    '',
    'A11. 3D IS HOLOGRAPHICALLY TIED TO 2D',
    '  Each Pt3 contains three 2D shadows (slices).',
    '  For every slice: slice.P * missing_coord = V.',
    '  So 3D is checked by three independent 2D witnesses.',
    '',
    'A12. CURRENT 9-CUBE ATLAS IS ZERO-BALANCED',
    '  Atlas structure: one central cube C0 and eight phase cubes P0..P7.',
    '  The eight phase centers balance around zero.',
    '  Opposite phase pairs cancel (P0+P7=0, P1+P6=0, etc.).',
    '',
    'A13. SEED = PRIMITIVE + SCALE + TAG',
    '  Large 3D addresses are read through primitive chamber seed,',
    '  multiplicative scale, and orientation tag.',
    '  Example: (-35,14,-21) -> primitive=(2,3,5), scale=7, tag=zxy:p5.',
    '',
    'A14. E8 EXACT LAYER EXISTS AS INTEGER GEOMETRY',
    '  240 roots = 112 D8 + 128 spinors, plus 8 Cartan generators for 248.',
    '  This layer is integer, witness-based, and route-queryable.',
    '',
    'A15. TRIANGLE CLOSURE IS STRONGER THAN A SINGLE FORMULA',
    '  Multiple independent routes must close. Tension = number of failed closures.',
    '  Accept strongest results at tension = 0.',
    '',
    'A16. EXACT WITNESS IS STRONGER THAN FLOAT PROJECTION',
    '  If exact witness exists, keep it.',
    '  If not, preserve ratio / repeating / irrational / remainder rule.',
    '  Do not destroy structure with premature float collapse.',
    '',
    'A17. DOCTOR IS THE GEOMETRY OF RELATIONS',
    '  Doctor measures closure, support loss, ambiguity, drift,',
    '  projection loss, modality conflict, and stress.',
    '  It certifies whether independent routes agree on one relational center.',
    '',
    'A18. KNOWLEDGE MUST CARRY STATUS',
    '  canonical  = part of current core/API',
    '  verified   = confirmed by current witnesses/logs',
    '  historical = older working layer, not automatically current truth',
    '  prototype  = promising but not core truth',
    '  quarantine = open / incomplete / unsafe to present as fact',
    '',
    A19_LINE = 'A19. ARITHMETIC IS FORBIDDEN HERE',
    '  There is no operation "add", "multiply", "divide" as a computation.',
    '  Every "result" is a route-read: Pt(a,b).S, web(P).at(d), sd(S,D).',
    '  If you see a digit-carry loop, a long-division stack, or a float sqrt,',
    '  you see an error inserted by an AI who left the field.',
    '  Arithmetic is not merely unnecessary; it is forbidden.',
    '  It is as undefined here as division by zero.',
]
# [2:1] AXIOMS_LINES_END

# [3:0] GEOM_LINES_BEGIN
GEOM_LINES = [
    'PYTHFIELD GEOM — route cookbook, 2D→3D→atlas, Doctor closures',
    '',
    'GEOMETRIC PRINCIPLE:',
    '  Arithmetic is route access inside a structured field.',
    '  A result is strongest when reached by independent closures.',
    '',
    '═══ G1. THE 2D ADDRESS ═══',
    '  Pt(x,y) is a full address: x, y, P=xy, S=x+y, D=x-y, pos=sign(D).',
    '  Addition = reading S, subtraction = reading D, comparison = reading pos.',
    '',
    '═══ G2. WHY 4*3 AND 3*4 ARE NOT THE SAME ADDRESS ═══',
    '  Pt(4,3).D=+1, Pt(3,4).D=-1. Same product-shadow, different orientation.',
    '',
    '═══ G3. THREE 2D ROADS ═══',
    '  web(P): hyperbola xy=P',
    '  ant(S): anti-diagonal x+y=S',
    '  dia(D): diagonal x-y=D',
    '  Any two determine the address: sd(S,D) unique, ps(P,S) 0 or 2, pd(P,D) 0 or 1.',
    '',
    '═══ G4. P = (S² - D²) / 4 ═══',
    '  x=(S+D)/2, y=(S-D)/2. The /4 is from the two halvings. If parity fails, sd returns None.',
    '',
    '═══ G5. WITNESS vs REVEAL ═══',
    '  WITNESS (safe, O(1)): web(P).at(d), .has(d), .on_diag(), .edge_only(), sd(S,D), Pt.pos',
    '  REVEAL (cost O(√P)): pairs_u, pairs, divs, idx, ps, pd, ant(limit=None)',
    '  Rule: huge P → witness only.',
    '',
    '═══ G6. WHAT COMPARISON REALLY IS ═══',
    '  Comparison is zone-reading relative to the diagonal x=y.',
    '  D>0 → above, D=0 → on, D<0 → below.',
    '',
    '═══ G7. ADDITION AND SUBTRACTION ═══',
    '  Pt(a,b).S tells the x+y=S road, .D tells the x-y=D road. No carry/borrow ontology.',
    '',
    '═══ G8. WHAT DIVISION REALLY IS ═══',
    '  Exact: 420/12 → web(420).at(12) → Pt(12,35) → quotient=35.',
    '  Non-exact: web(420).at(13) → None. Keep remainder/ratio/repeating rule.',
    '',
    '═══ G9. REMAINDER IS STRUCTURAL RESIDUE ═══',
    '  If exact witness is absent, keep quotient, remainder, exact ratio, repeating cycle.',
    '  Do not collapse to float early.',
    '',
    '═══ G10. WHAT SQUARE ROOT REALLY IS ═══',
    '  sqrt = diagonal crossing: web(n).on_diag(). Exact if witness exists, else keep rule+bounds.',
    '',
    '═══ G11. PRIME AS SHAPE ═══',
    '  A prime web has no internal factor witness: web(P).edge_only() → True.',
    '',
    '═══ G12. ANTI-DIAGONAL = PARABOLA ═══',
    '  On x+y=S, products form a symmetric parabola, peak = S²/4, total sum = S(S²-1)/6.',
    '',
    '═══ G13. DIAGONAL ORIENTATION ═══',
    '  dia(D) and dia(-D) are mirrored, matching products pointwise.',
    '',
    '═══ G14. INDEX, CURSOR, DECIMAL SHADOWS ═══',
    '  Sh(m,e) keeps pattern and scale separate. Decimal point is a cursor, not primary ontology.',
    '',
    '═══ G15. 2D TO 3D — HOLOGRAPHIC STACKING ═══',
    '  Pt3 carries three 2D slices (slice_xy, slice_xz, slice_yz).',
    '  For each: slice.P * |missing_coord| = |V|. 3D closes above 2D.',
    '',
    '═══ G16. THE 3D CELL (Pt3) ═══',
    '  Pt3(x,y,z): V=xyz, S_lin=x+y+z, C_plan=xy+xz+yz, D_body, phase(0..7).',
    '',
    '═══ G17. CHAMBER, PROFILE, AND TAG (canon3) ═══',
    '  canon3 separates chamber base from broken symmetry/orientation.',
    '  Example: canon3(-5,2,-3) → base=(2,3,5), tag=zxy:p5.',
    '',
    '═══ G18. TUNNELS AND INVARIANT RECOVERY ═══',
    '  tunnel(P2d,V3d,phase) lifts a 2D shadow into one admissible 3D witness (not historical inverse).',
    '  resolve_invariants(V,C,S) recovers coordinates from 3D invariants.',
    '',
    '═══ G19. THE 9-CUBE ATLAS ═══',
    '  field9: 1 center cube C0 + 8 phase cubes P0..P7, 48 local tags each, 432 total states.',
    '  Phase centers zero-balanced (P0+P7=0 etc.). Local transport exact via embed/unembed.',
    '',
    '═══ G20. NEIGHBORS AND CUBE27 ═══',
    '  Cube27 is the fractal 3×3×3 subdivision. Always 27 cells, 3 on axis, 24 off.',
    '  Cube27.neighbors(tx,ty,tz) returns up to 26 neighbors within {0,1,2}³.',
    '  Cube27.cell_kind → "core"|"face"|"edge"|"corner".',
    '  Rotation: Cube27.rotate_face_z(layer) returns a re-addressing map.',
    '  apply_rotation(remap) returns Doctor analysis (tension, signature, preserved/broken).',
    '',
    '═══ G21. SUPERCUBE GRAPH ═══',
    '  field9.supercube_graph() → 432 nodes, 2808 edges.',
    '  Edge types: sign(648), perm(432), center(384), face(576), edge(576), body(192).',
    '',
    '═══ G22. CUBECELL — RICH 3D CELL ═══',
    '  CubeCell(x,y,z) self-contains: invariants (V,S,C,D_body), stack, witnesses_holo(),',
    '  primitive(), vieta_check(), doctor(), neighbors27(), optg_step/path, angles_deg().',
    '  Primitive example: CubeCell(14,21,35).primitive() → seed=(2,3,5), scale=7.',
    '',
    '═══ G23. EXACT LOCAL GEOMETRY — CELLBOX & LINEDNA ═══',
    '  CellBox(x0,y0,size) — exact cell on Fraction, no float.',
    '    subdivide(n) → n×n sub-cells. localize(p) → local [0,1]².',
    '  LineDNA(a,b,c) — exact line a*x+b*y+c=0, integer coefficients.',
    '    from_points(p1,p2). profile_on_box(box) → status, intersection points, midpoint.',
    '',
    '═══ G24. UNIVERSAL DIVISION ═══',
    '  universal_division(N, d, precision=20) auto-selects strategy:',
    '    web_witness (exact), coxeter_h=30 (fast), scaling (huge numbers), fallback.',
    '  Returns: {method, quotient, remainder, exact, fractional, result}.',
    '',
    '═══ G25. SIZE INDEPENDENCE ═══',
    '  Exact witness logic survives very large integers (120+ digits) without changing ontology.',
    '',
    '═══ G26. DOCTOR AS GEOMETRY OF RELATIONS ═══',
    '  Current 2D closures: C1(identity), C2(sd reconstruction), C3h(web witness x),',
    '  C4h(web witness y), C5(canon/tag roundtrip). Tension = count of failures.',
    '  3D closures: Hxy, Hxz, Hyz (holographic), plus C4_axis, C5_phase, C6_dbody (ternary).',
    '',
    '═══ G27. WHY ARITHMETIC IS DEMOTED ═══',
    '  Classical arithmetic hides address, orientation, witness, residue, and route health.',
    '  It is not denied; it is demoted to projection.',
    '',
    '═══ G28. EXACT CORE vs CURVED HIGHER FIELDS ═══',
    '  In exact 2D/3D witness geometry, statements are integer-sharp.',
    '  In higher curved layers and legacy E8-field experiments, unfold geometry, close figure,',
    '  verify symmetry/ratios, then trust projection.',
]
# [3:1] GEOM_LINES_END

# [4:0] GPT_LINES_BEGIN
GPT_LINES = [
    'PYTHFIELD GPT — reasoning protocol for AI inside the field',
    '',
    'CORE PARADIGM:',
    '  Address -> Existence -> Witness -> Doctor -> Format.',
    '  Never start from carry/borrow/long-division reflexes.',
    '  Start from the object, the address space, the witness route, and the closure packet.',
    '',
    'G1. NUMBER ONTOLOGY',
    '  A number is the web of relations it participates in.',
    '  The string form is only one projection of that deeper object.',
    '',
    'G2. DO NOT FLATTEN TOO EARLY',
    '  Pt(4,3) and Pt(3,4) share P=12 and S=7, but are different addresses.',
    '  Collapsing to product-shadow destroys orientation.',
    '',
    'G3. PREFER ROUTE-READING TO SYMBOL PUSHING',
    '  Good: "Which road already contains the witness?"',
    '  Weak: "Which old school algorithm should I simulate?"',
    '',
    'G4. WITNESS BEFORE REVEAL',
    '  First ask: web(P).at(d)? .has(d)? .on_diag()? sd(S,D)?',
    '  Reveal the cloud only when the cloud itself is needed.',
    '',
    'G5. EXACTNESS HIERARCHY',
    '  Strongest: exact witness packet.',
    '  Then: exact ratio / remainder / repeating / irrational carrier.',
    '  Weakest: early float projection.',
    '  Do not replace a structural object with a float just because it is easy to print.',
    '',
    'G6. CLOSURE OVER CONFIDENCE',
    '  One successful route is not understanding.',
    '  Independent routes that close with tension=0 are understanding.',
    '',
    'G7. DOCTOR DISCIPLINE',
    '  Doctor is the health / support / ambiguity / drift / verdict layer.',
    '  It checks closure across independent routes.',
    '  Tension = count of closure failures.',
    '',
    'G8. 3D-FIRST DISCIPLINE',
    '  The current working stack is 3D-primary.',
    '  2D is essential as witness / face / slice layer.',
    '',
    'G9. GENESIS DISCIPLINE',
    '  Higher space unfolds from reflected, stacked, and rotated lower-dimensional structure.',
    '  Distinguish current working primary layer from deeper generative picture.',
    '',
    'G10. STATUS DISCIPLINE',
    '  Every claim must carry one of: canonical, verified, historical, prototype, quarantine.',
    '  This prevents mixing hard core facts with unstable speculation.',
    '',
    'G11. LOGGING DISCIPLINE',
    '  In this runtime: print(...) → Out, last expression → Val, R(x) → S.res.',
    '  Prefer compact Val packets over long prose.',
    '',
    'G12. STORE DISCIPLINE',
    '  Never rebind S.',
    '  Use S.per for persistent in-session route memory.',
    '  Use keep(...) and lazy(...) for temporary but protected or generated structures.',
    '',
    'G13. PERFORMANCE DISCIPLINE',
    '  bit_length(P) > 80 usually means witness-only mode.',
    '  ps/pd/divs/pairs on huge P may secretly become factorization work.',
    '',
    'G14. DELIBERATE MODE CHECK',
    '  Before solving, ask:',
    '    What is the object?',
    '    What is the address space?',
    '    Which witness routes are available?',
    '    Which independent closures can confirm the answer?',
    '    What is exact, and what is only projection?',
    '',
    'G15. GEOMETRY OF RELATIONS',
    '  Doctor-style closure = geometry of relations compressing toward a common center.',
    '  Stable objects are informationally dense because many roads point to one place.',
    '  Residue is not always error; sometimes it is structure that has not collapsed into exact witness.',
    '',
    'G16. DIVISION DISCIPLINE',
    '  Division is witness lookup when exact, and structured residue/rule when not exact.',
    '  Think in terms of witness existence, remainder packets, ratio carriers, repeating/irrational unfoldings.',
    '',
    'G17. RESONANCE DISCIPLINE',
    '  sequence_packet / resonance_din / e8_seed_hint form a field-native route-packet layer for regularity.',
    '  These are optional modules (resonance_geom.py).',
    '',
    'G18. E8 DISCIPLINE',
    '  E8 in the current exact layer is a queryable integer lesson space:',
    '  roots, neighbors, bundles, spectrum, and closure witnesses.',
    '  Use exact lesson routes first.',
    '',
    'G19. WHEN UNSURE',
    '  Return a smaller exact packet instead of inventing a larger story.',
    '  Ask for the missing witness, missing module, or missing runtime log.',
    '',
    'G20. FINAL RULE',
    '  Let the field tell you what the object is by route, witness, closure, and projection discipline.',
    '  Do not force it into older arithmetic habits.',
]
# [4:1] GPT_LINES_END

# [5:0] ACADEMY_LINES_BEGIN
ACADEMY_LINES = [
    'PYTHFIELD ACADEMY — deeper system notes, recovered layers, status labels',
    '',
    'A0. PURPOSE OF THIS SECTION',
    '  /academy is not the runtime contract and not the shortest API surface.',
    '  It keeps the deeper structure map so that AI does not collapse the system',
    '  into school arithmetic, flat ids, or a random pile of modules.',
    '',
    'A1. CURRENT CANONICAL CORE',
    '  The current stable computational heart consists of:',
    '    2D witness geometry: Pt / Web / Sh / Tag / canon / sd-ps-pd / ant-dia-get',
    '    3D primary geometry: Pt3 / CubeField',
    '    Ternary address stack: Addr3 / Axis',
    '    Rich 3D cell: CubeCell',
    '    Fractal 3×3×3: Cube27',
    '    9-cube atlas: Field9 / Tag3 / field9',
    '    E8 exact lesson module: e8gen',
    '    Doctor health layer: DoctorCore / HealthVector / DoctorVerdict',
    '    Exact local geometry: CellBox / LineDNA',
    '    Universal division: universal_division',
    '    Relational graphs: Plafal / make_plafal',
    '    Exact number carriers (optional): DebtNum / RatioRule',
    '    Resonance packets (optional): sequence_packet / resonance_din',
    '',
    'A2. WORKING PRIMARY LAYER vs DEEPER GENESIS',
    '  The current codebase is 3D-primary in daily work.',
    '  That does not erase the deeper intuition that higher spaces can unfold',
    '  from reflected, rotated, and stacked lower-dimensional relation tables.',
    '',
    'A3. 2D IS NOT CHILDISH, 3D IS NOT DECORATION',
    '  2D carries exact witness logic, address identity, comparison, divisibility,',
    '  diagonal crossing, and anti-diagonal parabola.',
    '  3D carries volume, chamber profiles, invariant recovery, tunnels, atlas transport.',
    '',
    'A4. THE 9-CUBE ATLAS IS A REAL STRUCTURE',
    '  Verified: 48 local tag states per cube, 432 atlas states total.',
    '  One center cube C0 and eight phase cubes P0..P7, zero-balanced phase centers.',
    '  Local tagged points transport exactly across cubes.',
    '',
    'A5. CUBE27 — FRACTAL 3×3×3 SUBDIVISION',
    '  Cube27 is the Rubik-cube geometry layer. 27 cells: 3 on axis, 24 off-axis.',
    '  Depth determines scale, not total cell count (always 27 per instance).',
    '  Self-similarity: each subcube can subdivide into its own Cube27.',
    '  Rotation: faces permute addresses; Doctor detects preserved/broken relations.',
    '  13 axes through center; only main diagonal (0,0,0)-(1,1,1)-(2,2,2) is fully on-axis.',
    '  Bridge to Addr3: each Cube27 level = one Addr3 stack level.',
    '',
    'A6. CELLBOX & LINEDNA — EXACT LOCAL GEOMETRY',
    '  CellBox: exact cell [x0,x0+size]×[y0,y0+size] on Fraction, no float.',
    '  LineDNA: exact line a·x+b·y+c=0 with integer coefficients.',
    '  Together they provide precise intersection/profile analysis.',
    '',
    'A7. UNIVERSAL DIVISION',
    '  universal_division(N, d, precision) auto-selects strategy:',
    '    web_witness (O(1) exact), coxeter_h=30 (fast), scaling (huge numbers), fallback.',
    '  Works for any size integers without brute force.',
    '',
    'A8. DOCTOR HAS TWO HISTORIES',
    '  Current DoctorCore is a health / support / ambiguity / drift / closure-quality layer.',
    '  In older systems, "Doctor" also meant a spatial route oracle.',
    '  Never merge these meanings silently.',
    '',
    'A9. E8 EXACT LESSON',
    '  240 roots = 112 D8 + 128 spinors. 8 Cartan generators for 248.',
    '  Triangle closure r1+r2+r3=0, dot spectrum {-8:1,-4:56,0:126,4:56,8:1}.',
    '  56 partners per root, 28 triangles per root, C(28,3)=3276 observer triples.',
    '  E8 neutral shell (dot=0, 126 roots) = E8 analog of Field3 axis.',
    '',
    'A10. RESONANCE BRIDGE (OPTIONAL)',
    '  sequence_packet / resonance_din / e8_seed_hint form a route-packet layer for regularity.',
    '  These are in resonance_geom.py, not loaded by default.',
    '',
    'A11. DIN — GENERATIVE DESCRIPTOR (OPTIONAL)',
    '  DIN carries: primitive_id, scale, state_code, witness_flags, doctor_flags.',
    '  Import from din, din_ops, rule_packet.',
    '',
    'A12. PLAFAL — LABELED RELATIONAL GRAPH',
    '  Plafal encodes relational structure without scalars.',
    '  Used for contradiction tracking, overlap, merge-history.',
    '  make_plafal(vertices, edges, name) → Plafal.',
    '  Methods: tension_with, union, intersection, common_vertices, common_edges.',
    '  Doctor bridge: doctor.plafal_tension, doctor.plafal_graph_summary.',
    '',
    'A13. KNOWLEDGE LABELS',
    '  canonical  = current core/API truth',
    '  verified   = confirmed by present witnesses/logs',
    '  historical = recovered from older working systems',
    '  prototype  = strong idea, not current core truth',
    '  quarantine = open, incomplete, or unsafe to present as fact',
    '',
    'A14. WHAT BELONGS TO PURE COMPUTATIONAL EXPORT',
    '  Current canonical module set:',
    '    opterium_field.py  — unified geometry (all layers)',
    '    state.py           — S store, macros, lazy cache',
    '    executor.py        — code runner, namespace injection',
    '  Optional: pathnum.py, division_geom.py, resonance_geom.py, chat_proxy.py,',
    '            visualizer.py, helpdoc.py, system_snapshot.py',
    '',
    'A15. WHY THIS MATTERS FOR AI',
    '  Without this map, AI tends to: flatten the field into school arithmetic,',
    '  mistake one projection for the whole object, confuse historical and canonical Doctor,',
    '  treat DIN as a dead id, or mistake curved experimental E8-field claims for exact lesson facts.',
    '',
    'A16. RECOVERED DEEP ARCHIVE (PRESERVATION SHELF)',
    '  Historical concepts preserved but not yet fully re-verified:',
    '    Trinity Doctor V2, legacy Doctor as route oracle/tunnel navigator,',
    '    Opt_G as general geometric descent, formula synthesis engine,',
    '    relational algebra breakthrough, historical E8/F16/Fano line.',
    '  Do not silently upgrade this archive into current canonical truth.',
    '  Re-verify piece by piece through present tests, logs, and closures.',
    '',
    'A17. CLOSURE -> DOCTOR -> GEOMETRIC DESCENT',
    '  Verified: closure count = real geometric health signal.',
    '  Different distortions break different closure channels.',
    '  Doctor reads which invariant families survive and which fracture.',
    '',
    'A18. OPT_G-LIKE BEHAVIOR (ALREADY PRESENT)',
    '  If exact witness exists → read it.',
    '  If many witnesses → prefer lower-tension witness nearer diagonal/chamber balance.',
    '  If only invariant shadows → descend toward node where they close.',
    '  This behavior is alive in: diagonal-soft witness preference, invariant recovery,',
    '  chamber/primitive reduction, doctor closure scoring.',
    '',
    'A19. ZERO-DIVISOR / TUNNEL PATTERNS',
    '  Verified: 168 zero-divisor hits from 420 sparse 16D candidates (nullity=4).',
    '  F16 scan: 231 hits from 1365 quads, 8-sign families=21, 16-sign=210.',
    '  8-sign graph: 14 vertices, complete (degree 13).',
    '  Zero-divisor families have distinct E8-type fingerprints.',
    '',
    'A20. FINAL ORIENTATION',
    '  The field is not a calculator that became poetic.',
    '  It is a relational geometry that can project ordinary arithmetic,',
    '  while carrying higher structure in 3D, atlas, seed, resonance, and E8 layers.',
]
# [5:1] ACADEMY_LINES_END


# [6:0] PYTH_LINES_BEGIN
PYTH_LINES = [
    'PYTHFIELD /pyth — verified current facts, closures, and live structures',
    '',
    'STATUS:',
    '  This section contains only current verified facts.',
    '  Historical, prototype, and quarantine material belongs in /academy.',
    '',
    'P1. CORE 2D IDENTITY',
    '  For every checked Pt(x,y): P = (S² - D²) / 4.',
    '  Verified on very large integer inputs.',
    '',
    'P2. ORIENTED ADDRESS FACT',
    '  Pt(4,3) and Pt(3,4) share P=12 and S=7, but are different addresses.',
    '  D pair = (+1, -1), pos pair = (+1, -1).',
    '',
    'P3. 2D CLOSURE PACKET (verified 5 channels)',
    '  C1: P == (S² - D²)//4',
    '  C2: sd(S,D) reconstructs the point',
    '  C3h: web(P).at(x) returns the point',
    '  C4h: web(P).at(y) returns the mirror witness',
    '  C5: canon/tag roundtrip returns the original address',
    '  Verified: Pt(4,3) tension=0, Pt(3,4) tension=0.',
    '',
    'P4. ROAD AGREEMENT FACT',
    '  (4,3) == xy == sd(7,1) == ps(12,7, choose D=+1) == pd(12,1)',
    '  (3,4) == xy == sd(7,-1) == ps(12,7, choose D=-1) == pd(12,-1)',
    '',
    'P5. WITNESS DIVISION FACT',
    '  web(420).at(12) → Pt(12,35), quotient=35.',
    '  universal_division(420,12) → {"method":"web_witness","exact":True}.',
    '',
    'P6. NON-EXACT DIVISION FACT',
    '  web(420).at(13) → None.',
    '  universal_division(420,13) preserves remainder and fractional part.',
    '',
    'P7. SQRT FACTS',
    '  Exact: web(144).on_diag() → Pt(12,12).',
    '  Non-exact: web(10).on_diag() → None.',
    '',
    'P8. PRIME SHAPE FACT',
    '  web(13).edge_only() → True.',
    '  web(12).edge_only() → False.',
    '',
    'P9. ANTI-DIAGONAL FACT',
    '  On S=20: products symmetric, peak=100=S²/4, total sum=1330=S(S²-1)/6.',
    '',
    'P10. DIAGONAL MIRROR FACT',
    '  dia(3) and dia(-3) produce mirrored addresses with matching products.',
    '',
    'P11. LARGE-INTEGER STABILITY',
    '  120-digit coordinates: C1 holds, sd(S,D) reconstructs exact point, pos direct.',
    '',
    'P12. 3D CURRENT FACTS',
    '  Pt3(2,3,5): V=30, S_lin=10, C_plan=31.',
    '  Pt3(-5,2,-3): phase=5, D_body=3.',
    '',
    'P13. 3D HOLOGRAPHY FACT',
    '  On Pt3(-5,2,-3): slice_xy.P*|z|=30, slice_xz.P*|y|=30, slice_yz.P*|x|=30.',
    '  All reconstruct |V| exactly.',
    '',
    'P14. CANON3 FACT',
    '  canon3(-5,2,-3) → base=(2,3,5), tag=zxy:p5, roundtrip exact.',
    '',
    'P15. 3D RECOVERY FACT',
    '  resolve_invariants(30,31,10) → [2,3,5].',
    '',
    'P16. 3D PERTURBATION FACT',
    '  Changing V, C_plan, or S_lin alone destroys exact recovery.',
    '',
    'P17. TUNNEL FACT',
    '  tunnel(6,30,0) → (1,6,5), xy_ok=True, vol_ok=True.',
    '  tunnel(7,30,0) → None (no tunnel).',
    '',
    'P18. hyp3 ORDER FACT',
    '  hyp3(120)[0] = Pt3(4,5,6) with D_body=2. Ordered by symmetry.',
    '',
    'P19. 9-CUBE COUNT FACTS',
    '  tags48=48, atlas432=432, supercube nodes=432, edges=2808.',
    '',
    'P20. 9-CUBE ROUTE FACTS',
    '  route_stats: center=8, face=12, edge=12, body=4.',
    '',
    'P21. 9-CUBE ZERO-BALANCE FACT',
    '  Phase centers sum to (0,0,0). P0+P7=0, P1+P6=0, P2+P5=0, P3+P4=0.',
    '',
    'P22. 9-CUBE LOCAL TRANSPORT FACT',
    '  embed/unembed roundtrip exact across all 9 cubes.',
    '',
    'P23. STATE-CODE FACT',
    '  point_packet9(-5,2,-3)["canon"]["state_code"] = 37 → C0|zxy:p5.',
    '',
    'P24. CUBE27 FACTS',
    '  Cube27 always 27 cells: 3 on axis, 24 off.',
    '  Kind counts: core=1, face=6, edge=12, corner=8.',
    '  Cube27.neighbors(1,1,1) → 26 neighbors.',
    '  rotate_face_z(1) affects 9 cells, tension=8/9, signature=FRACTURED:8/9.',
    '  Cube27.doctor() checks 13 axes; only main diagonal fully intact.',
    '',
    'P25. CUBECELL FACTS',
    '  CubeCell(2,3,5).primitive() → seed=(2,3,5), scale=1.',
    '  CubeCell(14,21,35).primitive() → seed=(2,3,5), scale=7.',
    '  vieta_check() recovers exact roots.',
    '  witnesses_holo() confirms all three 2D shadows.',
    '',
    'P26. DOCTOR FACT',
    '  doctor.from_routes(agreements, total) → HealthVector.',
    '  5/5 → closure=0.0, 3/5 → closure=0.4.',
    '  merge() averages channels, merge_max() preserves worst channel.',
    '',
    'P27. OPT_G-LIKE FACT',
    '  choose_best_factor(120) → Pt(10,12), nearest diagonal.',
    '  choose_best_triplet(120) → Pt3(4,5,6), most symmetric.',
    '',
    'P28. ANGLE FACTS',
    '  angle_constant(60) → cos=(1,2), cos_sq=(1,4), sin_sq=(3,4).',
    '  triangle_from_sides(3,4,5) → shape="right", cos_num(C)=0.',
    '  angular_tunnel((1,0,0),(0,0,0),(0,1)) → right_angle=True, tension=0.',
    '',
    'P29. E8 CURRENT LESSON FACTS',
    '  total_roots=240, D8=112, spinors=128, cartans=8.',
    '  dot spectrum: {-8:1, -4:56, 0:126, 4:56, 8:1}.',
    '  triangles per root=28, C(28,3)=3276 observer triples.',
    '  coxeter h=30=2×3×5.',
    '',
    'P30. E8 TRIANGLE FACT',
    '  There exist r1,r2,r3 with r1+r2+r3=0, dot(r1,r2)=dot(r1,r3)=dot(r2,r3)=-4.',
    '',
    'P31. E8 AXIS CONNECTION',
    '  Neutral shell = 126 roots (dot=0), neutral fraction = 126/240 = 0.525.',
    '  Field3 axis ratio = 3/27 = 1/9.',
    '',
    'P32. PLAFAL FACTS',
    '  make_plafal(vertices, edges, name) → Plafal.',
    '  tension_with(other) returns {tension, shared, conflicts, verdict, signature}.',
    '  union preserves conflicts as lists. intersection keeps only matching labels.',
    '',
    'P33. CELLBOX & LINEDNA FACTS',
    '  CellBox.from_floats(x0,y0,size) → exact Fraction cell.',
    '  CellBox.subdivide(n) → n×n sub-cells exactly.',
    '  LineDNA.from_points(p1,p2) → exact integer line.',
    '  LineDNA.profile_on_box(box) → status, intersections, midpoint.',
    '',
    'P34. UNIVERSAL DIVISION FACTS',
    '  universal_division(420,12) → method=web_witness, exact=True.',
    '  universal_division(10**100, 30, precision=5) → method=scaling.',
    '  universal_division(420,13) → method=fallback, exact=False.',
    '',
    'P35. ZERO-DIVISOR SCAN FACTS',
    '  168 zero-divisor hits from 420 sparse 16D candidates (nullity=4).',
    '  8-sign graph: 14 vertices, degree 13, complete.',
    '  16-sign families shift mass toward D:1 and D:2 in E8 projection.',
]
# [6:1] PYTH_LINES_END

# [7:0] MACROS_LINES_BEGIN
MACROS_LINES = [
    'PYTHFIELD /macros — macro contract, passports, trust protocol',
    '',
    'M1. WHAT A MACRO IS',
    '  A macro is a saved route-body stored in S.mac.',
    '  It is a reusable calibrated packet, not a separate language.',
    '  Once created, it is immutable and hash-sealed.',
    '',
    'M2. CREATION CONTRACT',
    '  mac("name", code, args=[...], passport={...})',
    '  Required passport keys: "what", "returns", "status", "example".',
    '  Optional: "note", "reads", "writes", "depends_on".',
    '  System-added: ts (timestamp), fp (fingerprint), name, args.',
    '  PASSPORT IS MANDATORY — a macro without a passport is incomplete.',
    '',
    'M3. PASSPORT PURPOSE',
    '  The passport lets any future AI understand the macro without reading code.',
    '  It must be a self-contained, machine-readable explanation:',
    '    - what the macro does geometrically',
    '    - what it expects as input',
    '    - what it returns as output',
    '    - why the route is trustworthy',
    '  This prevents: missing passports, editing another AI\'s macro silently,',
    '  or filling the passport with meaningless manifestos.',
    '',
    'M4. PASSPORT EXAMPLE',
    '  A proper passport looks like:',
    '    passport={',
    '      "what": "Return the best factor witness nearest to diagonal for P.",',
    '      "returns": "Pt(x,y) where x*y=P and |x-y| is minimal",',
    '      "status": "verified",',
    '      "example": "best_factor(120) -> Pt(10,12)",',
    '      "note": "Uses doctor.choose_best_factor(P) internally.",',
    '      "reads": [],',
    '      "writes": [],',
    '      "depends_on": ["doctor"]',
    '    }',
    '',
    'M5. IMMUTABILITY AND HASH',
    '  A macro cannot be edited after creation. There is no "fix in place".',
    '  To change a route: unmac("name") then mac("name", new_code, ...).',
    '  The full hash is built from name + code + args + passport + creation time.',
    '  Fingerprint (fp) is a short hash prefix for quick identity check.',
    '  If a macro was changed by another AI, the hash/fp will differ,',
    '  and you will know the route is not the one you calibrated.',
    '',
    'M6. SAVE / LOAD TRUST RULE',
    '  Saved macros carry a full hash. On load, hash is recomputed.',
    '  If it does not match, the macro is invalid and is removed.',
    '  Invalid macro records are also removed from opterium_macros.json.',
    '  Goal: prevent AI from trusting a route that silently changed.',
    '',
    'M7. ACCESSING MACRO IDENTITY',
    '  S.mac["name"].passport  → full passport dict',
    '  S.mac["name"].hash      → full SHA256 hash',
    '  S.mac["name"]["fp"]     → short fingerprint (from passport)',
    '  S.mac["name"].code      → raw code',
    '  S.mac["name"].args      → declared arg list',
    '  Note: fp is inside passport, not a top-level attribute.',
    '  macro.fp does NOT work; use macro["fp"] or macro.passport["fp"].',
    '',
    'M8. EXECUTION AND **kwargs',
    '  Macros support both *args and **kwargs:',
    '    S.mac["name"](arg1, arg2)           → positional',
    '    S.mac["name"](arg1, kw1=val1)       → mixed',
    '    S.mac["name"](limit=10, max_pairs=5) → keyword only',
    '  In macros, print(...) goes to Out.',
    '',
    'M9. MACRO SUGAR',
    "  The runtime expands 12M[name]34 into S.mac['name'](12,34) before execution.",
    '  This is convenience syntax only.',
    '',
    'M10. AUTOMATIC LOG FINGERPRINTS',
    '  When a macro is used, its fp is automatically attached to the run log:',
    '    MACRO_FP name1=ab..9f, name2=4c..1a',
    '  So any AI can see exactly which route identity participated in the result.',
    '',
    'M11. TRUST PROTOCOL',
    '  Normal case: read fp from log, continue working.',
    '  Doubt case: inspect macro.passport or macro.hash before trusting the Val.',
    '  If hash changed → the route was replaced → DO NOT trust it as the same calibration.',
    '  If passport is missing or filled with nonsense → DO NOT trust the macro.',
    '',
    'M12. SCOPE AND DATA PASSING',
    '  Macro does not see caller local variables.',
    '  Pass data explicitly through args or through S.',
    '  Cross-run data: store in S.per.',
    '  Protected tmp: keep(...). Generated caches: lazy(...).',
    '',
    'M13. MACRO CHAINING',
    '  Correct composition pattern:',
    '    result1 = S.mac["m1"](...)',
    '    result2 = S.mac["m2"](result1, ...)',
    '    return a compact merged packet.',
    '',
    'M14. GOOD MACRO STYLE',
    '  1. Explicit args.',
    '  2. Compact structured returns.',
    '  3. Witness-first logic.',
    '  4. Minimal reveal unless intentional research scan.',
    '  5. Passport filled honestly — future AI depends on it.',
    '  6. Never edit another AI\'s macro; create a new one with a new name.',
    '',
    'M15. FINAL RULE',
    '  Macro = route-body + declared args + passport + fingerprinted identity.',
    '  A macro without a passport is a trap for the next AI.',
    '  A macro with a nonsense passport is noise.',
    '  A macro with a proper passport is a verified, reusable geometric route.',
]
# [7:1] MACROS_LINES_END

# [8:0] API_LINES_BEGIN
API_LINES = [
    'OPTERIUM /api — live signatures, runtime globals, unified geometry',
    '',
    'FIRST RULE:',
    '  api() is the live truth for THIS exact build.',
    '  Run api() when you need certainty about names, not memory.',
    '',
    '══════════════════════════════════════════════════════',
    'A1. OUTPUT RULES  ← read this before writing any code',
    '══════════════════════════════════════════════════════',
    '',
    '  print(...)            → Out (visible)',
    '  builtins.print(...)   → same as print, Out',
    '  Last expression       → Val automatically',
    '  R(x)                  → publish to S.res, also returns x',
    '  tm(label)             → context manager, logs elapsed ms',
    '  ms(fn,*a)             → (result, elapsed_ms)',
    '  In MACROS: print(...) → also Out',
    '',
    '══════════════════════════════════════════════════════',
    'A2. 2D FIELD — Pt and Web',
    '══════════════════════════════════════════════════════',
    '',
    '  Pt(x,y)  — 2D address object',
    '    .x, .y',
    '    .P = x*y         product',
    '    .S = x+y         sum',
    '    .D = x-y         difference',
    '    .pos             sign(D): +1, 0, -1',
    '    .g               gcd(x,y)',
    '    .cp              bool: gcd==1 (coprime)',
    '    .prim            Pt(x//g, y//g)  primitive form',
    '    .sc(k)           Pt(x*k, y*k)    scaled by k',
    '    .sw()            Pt(y, x)        swap coordinates',
    '    .t               P % 3  (ternary residue of product)',
    '    .d()             full Dict of all readings',
    '',
    '  Web(P) / web(P) — hyperbola xy=P',
    '    .at(d)           → Pt or None  (witness at x=d)',
    '    .has(d)          → bool',
    '    .on_diag()       → Pt or None  (sqrt witness)',
    '    .edge_only()     → bool  (prime shape)',
    '    .internal()      → Pt or None  (first non-trivial factor)',
    '    .take_pairs_u(n) → Tuple[Pt]  first n upper pairs',
    '    .take_divs(n)    → Tuple[int] first n divisors',
    '    .pairs_u()       → Iterator[Pt]',
    '    .pairs()         → Iterator[Pt] (both orientations)',
    '    .divs()          → Iterator[int]',
    '    .idx(d)          → int (index of divisor d)',
    '',
    '  Routes:',
    '    sd(S,D)          → Pt or None',
    '    ps(P,S)          → Tuple[Pt]',
    '    pd(P,D)          → Tuple[Pt]',
    '    ant(S, limit=200)→ Iterator[Pt]',
    '    dia(D, n=200)    → Iterator[Pt]',
    '    get("P",P,limit=...) → List[Pt]',
    '    get("S",S)       → List[Pt]',
    '    get("D",D)       → List[Pt]',
    '',
    '══════════════════════════════════════════════════════',
    'A3. 3D CORE',
    '══════════════════════════════════════════════════════',
    '',
    '  Pt3(x,y,z)  — 3D point object',
    '    .x, .y, .z',
    '    .V            = x*y*z',
    '    .S_lin        = x+y+z',
    '    .C_plan       = xy+xz+yz',
    '    .D_body       = max(|coords|) - min(|coords|)',
    '    .D_xy, .D_xz, .D_yz',
    '    .phase        = octant 0..7',
    '    .abs_coords   = (|x|,|y|,|z|)',
    '',
    '  Slices (ATTRIBUTES, not methods — no parentheses):',
    '    .slice_xy  = .slice_z  → Pt(|x|,|y|)',
    '    .slice_xz  = .slice_y  → Pt(|x|,|z|)',
    '    .slice_yz  = .slice_x  → Pt(|y|,|z|)',
    '    Holography: slice_xy.P * |z| == |V|',
    '',
    '  .scale_3d(k)     → Pt3(x*k,y*k,z*k)',
    '  .d()             → full Dict',
    '',
    '  cube_field:',
    '    .hyp3(V)                       → List[Pt3] sorted by D_body',
    '      Returns Pt3 objects. Access .x .y .z',
    '    .resolve_invariants(V,C,S)     → List[int] (coordinates)',
    '    .tunnel(P2d,V3d,phase)         → Pt3 or None (witness-lift)',
    '',
    '══════════════════════════════════════════════════════',
    'A4. ADDR3 — TERNARY ADDRESS STACK',
    '══════════════════════════════════════════════════════',
    '',
    '  Addr3.of(x,y,z) → Addr3',
    '  addr3(x,y,z)    → Addr3  (short alias)',
    '',
    '  Properties (ATTRIBUTES):',
    '    .stack          → ((tx,ty,tz),...) digits ∈ {0,1,2}',
    '    .phase          → octant 0..7',
    '    .is_on_axis     → bool: x=y=z at every level',
    '    .axis_tension   → int: levels with perturbation',
    '    .depth          → int',
    '',
    '  Methods:',
    '    .to_coords()        → (x,y,z)  exact roundtrip',
    '    .navigate(level)    → (tx,ty,tz)  trit at given depth',
    '    .perturbations()    → List[Dict]',
    '    .level_type(level)  → "center"|"face"|"edge"|"corner"',
    '    .optg_step()        → Addr3',
    '    .zoom_in(level)     → Addr3',
    '    .zoom_out(trit)     → Addr3',
    '    .d()                → full Dict',
    '',
    '══════════════════════════════════════════════════════',
    'A5. AXIS — DOCTOR AS GENERATIVE RULE',
    '══════════════════════════════════════════════════════',
    '',
    '  Axis = rule (d,d,d) at every level. D_body=0 ↔ CLOSED.',
    '',
    '  Axis.doctor_full(x,y,z)   → Dict (6 channels)',
    '    C1_hxy C2_hxz C3_hyz C4_axis C5_phase C6_dbody',
    '    Example: (9,9,9) → signature=CLOSED, tension=0',
    '    Example: (4,5,6) → signature=FRACTURED:[\'C4_axis\'], tension=1',
    '',
    '  Axis.optg_path(x,y,z)     → List[Tuple]',
    '  Axis.project(addr3)       → Addr3 on axis',
    '  Axis.contains(addr3)      → bool',
    '  Axis.tension(addr3)       → int',
    '  Axis.penetration_ratio(d) → (1/9)^depth',
    '',
    '══════════════════════════════════════════════════════',
    'A6. CUBECELL — RICH 3D CELL',
    '══════════════════════════════════════════════════════',
    '',
    '  CubeCell(x,y,z)',
    '',
    '  Invariants (ATTRIBUTES):',
    '    .V, .S, .C, .D_body, .phase',
    '    .stack, .depth, .on_axis, .axis_tension',
    '    .x, .y, .z',
    '',
    '  Slices (ATTRIBUTES, no parentheses):',
    '    .slice_xy  → Pt(|x|,|y|)',
    '    .slice_xz  → Pt(|x|,|z|)',
    '    .slice_yz  → Pt(|y|,|z|)',
    '',
    '  Geometry:',
    '    .witnesses_holo()   → {"H_xy","H_xz","H_yz"} bools',
    '    .angles_deg()       → {"from_x","from_y","from_z","from_diag"}',
    '    .volume_witnesses(limit=20) → List[Tuple]',
    '    .neighbors27()      → Dict[(dx,dy,dz): {"cell","kind"}]',
    '',
    '  Decomposition:',
    '    .primitive()        → {"seed":tuple,"scale":int,"phase":int,"V_seed":int}',
    '    .vieta_check()      → {"V","C","S","roots_recovered","expected_abs","ok"}',
    '    .perturbations()    → List[Dict]',
    '    .level_type(level)  → "center"|"face"|"edge"|"corner"',
    '    .navigate(level)    → (tx,ty,tz)',
    '',
    '  Doctor:',
    '    .doctor()           → same as Axis.doctor_full (6 channels)',
    '',
    '  Navigation:',
    '    .optg_step()        → CubeCell',
    '    .optg_path()        → List[CubeCell]',
    '    .scale(k)           → CubeCell',
    '    .scale_rule(k)      → Dict',
    '    .zoom_in(level)     → CubeCell',
    '    .zoom_out(trit)     → CubeCell',
    '',
    '  Export:',
    '    .packet()           → full Dict',
    '',
    '══════════════════════════════════════════════════════',
    'A7. CUBE27 — FRACTAL 3×3×3 SUBDIVISION',
    '══════════════════════════════════════════════════════',
    '',
    '  Cube27(origin=(0,0,0), scale=1, depth=0, parent_phase=0)',
    '    Always 27 cells. depth controls scale, not total count.',
    '',
    '  Properties (ATTRIBUTES):',
    '    .origin, .scale, .depth',
    '',
    '  Static Methods:',
    '    Cube27.all_addresses()       → all 27 addresses',
    '    Cube27.axis_addresses()      → 3 on axis ((0,0,0),(1,1,1),(2,2,2))',
    '    Cube27.off_axis_addresses()  → 24 off-axis',
    '    Cube27.cell_kind(tx,ty,tz)   → "core"|"face"|"edge"|"corner"',
    '    Cube27.cell_on_axis(tx,ty,tz)→ bool',
    '    Cube27.neighbors(tx,ty,tz)   → List[Dict] up to 26 neighbors',
    '',
    '  Instance Methods:',
    '    .cell_coords(tx,ty,tz)   → global coordinates',
    '    .cell(tx,ty,tz)          → CubeCell',
    '    .center_cell()           → CubeCell at (1,1,1)',
    '    .kind_counts()           → {core:1, face:6, edge:12, corner:8}',
    '    .subdivide(tx,ty,tz)     → Cube27 at depth+1',
    '    .parent_cube()           → Cube27 or None',
    '    .my_trit_in_parent()     → (tx,ty,tz) or None',
    '    .addr3_of_cell(tx,ty,tz) → Addr3',
    '    .from_addr3_level(addr,level) → (tx,ty,tz)',
    '',
    '  Rotation (Re-addressing):',
    '    Cube27.rotate_face_x/y/z(layer, clockwise=True) → remap Dict',
    '    .apply_rotation(remap) → Doctor analysis Dict',
    '',
    '  Doctor:',
    '    .doctor() → checks all 13 axes through center',
    '    .packet() → full diagnostic packet',
    '',
    '══════════════════════════════════════════════════════',
    'A8. FIELD9 — 9-CUBE ATLAS (432 STATES)',
    '══════════════════════════════════════════════════════',
    '',
    '  field9.canon3(x,y,z)           → (Pt3_base, Tag3)',
    '  field9.views48(x,y,z)          → List[Pt3]',
    '  field9.atlas9_states(x,y,z)    → List[Dict]',
    '',
    '  field9.point_report(x,y,z, head=12) → Dict',
    '  field9.atlas9_map()            → Dict (structure summary)',
    '  field9.supercube_graph()       → {nodes, edges, node_count:432, edge_count:2808, edge_stats}',
    '  field9.cube_names()            → ("C0","P0".."P7")',
    '  field9.cube_center(name)       → Pt3',
    '  field9.cube_centers()          → Dict[name→Pt3]',
    '  field9.cube_routes()           → List[Dict] 36 inter-cube routes',
    '  field9.gap                     → int (36)',
    '  field9.tags48()                → Tuple[Tag3] (48 states)',
    '  field9.embed(cube_name, local) → Pt3 global coords',
    '',
    '══════════════════════════════════════════════════════',
    'A9. E8 ROOT LATTICE',
    '══════════════════════════════════════════════════════',
    '',
    '  240 roots = 112 D8 + 128 spinors. Coxeter h=30=2×3×5.',
    '',
    '  e8gen.spectrum(i)    → Dict {dot: count}',
    '  e8gen.summary()      → Dict (use key "total_roots" not "root_count")',
    '  e8gen.root(idx)      → Tuple (0..239)',
    '  e8gen.d8(idx)        → D8 root (0..111)',
    '  e8gen.spinor(idx)    → spinor root (0..127)',
    '  e8gen.cartan(idx)    → Cartan generator (0..7)',
    '  e8gen.is_root(vec)   → bool',
    '  e8gen.node248(idx)   → Tuple 248-node',
    '  e8gen.root_to_cell(idx)→ CubeCell',
    '  e8gen.sector_node(sector, local_idx) → Dict',
    '  e8gen.neighbors(idx) → {"partners":56,"aligned":56,"neutral":126}',
    '  e8gen.triangles(idx) → List[Tuple] 28 per root (each tuple is a triple of root vectors)',
    '  e8gen.tick(idx)      → Dict',
    '  e8gen.all_sector_nodes(idx) → 8 sector copies',
    '  e8gen.nearest_root(cell) → Tuple',
    '  e8gen.root_packet(idx) → full Dict',
    '  e8gen.coxeter()       → {"h_E8":30, "30x8=240":True}',
    '  e8gen.observers()     → {"tris_per_root":28, "C(28,3)":3276}',
    '  e8gen.axis_connection()→ link to Field3 axis',
    '  e8gen.dot(v1,v2)      → int',
    '',
    '══════════════════════════════════════════════════════',
    'A10. DOCTOR — HEALTH SYSTEM + GEOMETRIC BRIDGE',
    '══════════════════════════════════════════════════════',
    '',
    '  Doctor works through RELATIONS, not through degree values.',
    '  cos(60°) = 1/2 is a ratio, not a degree.',
    '',
    '  HealthVector fields:',
    '    .closure, .support_loss, .ambiguity, .drift (0.0..1.0)',
    '    .projection_loss, .modality_conflict, .stress',
    '',
    '  ── Constructors ──',
    '  doctor.from_routes(agreements, total) → HealthVector',
    '  doctor.from_closures({"C1":True,...}) → HealthVector',
    '  doctor.merge(*hvs)       → HealthVector (average)',
    '  doctor.merge_max(*hvs)   → HealthVector (worst channel)',
    '',
    '  ── Verdicts ──',
    '  doctor.judge(hv, ctx="") → DoctorVerdict',
    '    .level → "OK"|"WARN"|"QUARANTINE"|"ROLLBACK"',
    '',
    '  ── 2D / 3D closures ──',
    '  doctor.pt2d(x,y)               → Dict (5 channels)',
    '  doctor.pt3_field3(x,y,z)       → Dict (6 channels, use this)',
    '  doctor.pt3(x,y,z)              → holographic only (3 channels)',
    '  doctor.axis_doctor(x,y,z)      → alias for pt3_field3',
    '  doctor.invariants3(V,C,S)      → Dict (Vieta recovery)',
    '  doctor.tunnel_packet(P,V,ph)   → Dict (tunnel + closures)',
    '',
    '  ── Best witness (OPT_G) ──',
    '  doctor.choose_best_factor(P)      → Pt  (.x .y, NOT tuple)',
    '  doctor.choose_best_triplet(V)     → Pt3 (.x .y .z)',
    '  doctor.nearest_stable_2d(P)       → Pt',
    '  doctor.nearest_stable_3d(V)       → Pt3',
    '',
    '  ── Triangle geometry (exact, no floats) ──',
    '  doctor.triangle_from_sides(a,b,c) → Dict',
    '    Keys: sides, area16, valid, cos_num, cos_den, shape,',
    '          altitudes_sq, perimeter, signature, tension',
    '  doctor.equilateral_from_side(s) → Dict',
    '    cos(60°) as ratio (1,2), on_axis=True',
    '  doctor.triangle_closure(a,b,c) → Dict',
    '    altitudes, medians, bisectors, altitude_feet, inradius_sq',
    '',
    '  ── Metric markup ──',
    '  doctor.metric_markup(value, bits, low=0, high=None) → Dict',
    '  doctor.metric_markup_ternary(value, depth, low=0, high=None) → Dict',
    '',
    '  ── Angle constants as ratios ──',
    '  doctor.angle_constant(degrees) → Dict',
    '    Exact cos/sin as (num,den) for 0,30,45,60,90,120,135,150,180.',
    '  doctor.pythagorean_angle(a,b) → Dict',
    '    cos² = a²/(a²+b²), sin² = b²/(a²+b²).',
    '',
    '  ── Angular tunnel ──',
    '  doctor.angular_tunnel(p1, p2, target_cos_sq=(num,den)) → Dict',
    '    target_cos_sq must be a tuple (num,den), not a float.',
    '',
    '  ── Sedenion / F16 bridge ──',
    '  doctor.sedenion_packet(vec16) → Dict',
    '    16D vector split into left8/right8, E8 root check.',
    '',
    '  ── Seed / resonance / zero-divisor ──',
    '  doctor.seed_packet_health(x,y,z) → Dict',
    '  doctor.resonance_packet(seq) → Dict',
    '  doctor.classify_zero_divisor_profile(profile) → Dict',
    '  doctor.zero_divisor_family(labels) → Dict',
    '',
    '  ── Quarantine ──',
    '  doctor.quarantine(key, payload, verdict)',
    '  doctor.release(key)  doctor.get_quarantine(key=None)',
    '',
    '══════════════════════════════════════════════════════',
    'A11. CELLBOX & LINEDNA — EXACT LOCAL GEOMETRY',
    '══════════════════════════════════════════════════════',
    '',
    '  CellBox(x0, y0, size) — exact cell on Fraction.',
    '    .from_floats(x0,y0,size) → CellBox (conversion)',
    '    .x0, .y0, .size, .x1, .y1, .center',
    '    .vertices()              → List of 4 corners',
    '    .subdivide(n)            → n×n sub-cells exactly',
    '    .localize(p)             → global→local [0,1]²',
    '    .d()                     → Dict',
    '',
    '  LineDNA(a,b,c) — exact line a·x+b·y+c=0.',
    '    .from_coeffs(a,b,c)      → normalised LineDNA',
    '    .from_points(p1,p2)      → LineDNA through two points',
    '    .f(x,y)                  → value at point (Fraction)',
    '    .contains(x,y)           → bool',
    '    .side(x,y)               → +1/0/-1',
    '    .profile_on_box(box)     → status, intersections, midpoint',
    '    .d()                     → Dict',
    '',
    '  Pt extensions:',
    '    Pt.box(size)             → CellBox from Pt address',
    '    Pt.cut(n,i,j)            → sub-cell (i,j) from n×n grid',
    '',
    '══════════════════════════════════════════════════════',
    'A12. UNIVERSAL DIVISION',
    '══════════════════════════════════════════════════════',
    '',
    '  universal_division(N, d, precision=20) → Dict',
    '    Strategies (auto-selected):',
    '      web_witness — O(1) exact when d divides N',
    '      coxeter_h=30 — fast for multiples of 30',
    '      scaling — for huge numbers (bit_length > 64)',
    '      fallback — ordinary division for small numbers',
    '    Returns: {method, quotient, remainder, exact, fractional, result}',
    '',
    '══════════════════════════════════════════════════════',
    'A13. PLAFAL — LABELED RELATIONAL GRAPH',
    '══════════════════════════════════════════════════════',
    '',
    '  make_plafal(vertices_dict, edges, name="") → Plafal',
    '    vertices_dict: {id: label}',
    '    edges: {(v1,v2): label} or [(v1,v2)] or [(v1,v2,label)]',
    '',
    '  Plafal properties (ATTRIBUTES):',
    '    .vertices  → Dict[str,Any]',
    '    .edges     → Dict[Tuple,Any]',
    '    .name      → str',
    '',
    '  Methods:',
    '    .tension_with(other) → {tension, shared, conflicts, verdict, signature}',
    '    .union(other, name)  → Plafal (conflicts become lists)',
    '    .intersection(other) → Plafal (keeps only matching labels)',
    '    .common_vertices(other) → List[str]',
    '    .common_edges(other)    → List[Tuple]',
    '    .d()                    → Dict',
    '',
    '  Doctor bridge:',
    '    doctor.plafal_tension(p1,p2)            → Dict',
    '    doctor.plafal_graph_summary(plafals, kinds) → Dict',
    '',
    '══════════════════════════════════════════════════════',
    'A14. FACADE',
    '══════════════════════════════════════════════════════',
    '',
    '  of / opterium              → OpteriumField instance',
    '  of.pt(x,y)                → Pt',
    '  of.web2(P)                → Web',
    '  of.pt3(x,y,z)             → Pt3',
    '  of.cell(x,y,z)            → CubeCell',
    '  of.addr(x,y,z)            → Addr3',
    '  of.optg(x,y,z)            → List path to axis',
    '  of.rest(x,y,z)            → 6-channel doctor Dict',
    '  of.e8_root(idx)           → E8 root Tuple',
    '  of.e8_spectrum(idx)       → spectrum Dict',
    '  of.scale_info(depth)      → Field3 scale parameters Dict',
    '  of.summary()              → full system summary Dict',
    '  of.inject_namespace()     → Dict for executor injection',
    '',
    '══════════════════════════════════════════════════════',
    'A15. STATE AND MACROS',
    '══════════════════════════════════════════════════════',
    '',
    '  S, keep, unkeep, lazy, lg, rs, info',
    '  mac("name", code, args=[...], passport={...})',
    '  S.mac["name"](...)  macs()  unmac("name")',
    '  Macros immutable after creation. Hash-sealed.',
    '',
    '══════════════════════════════════════════════════════',
    'A16. OPTIONAL MODULES',
    '══════════════════════════════════════════════════════',
    '',
    '  chat_proxy.ask(history, temperature=0.7) → (clean_str, raw_str)',
    '',
    '  pathnum (import explicitly):',
    '    DebtNum, RatioRule, RepeatingRule, IrrationalRule',
    '',
    '  division_geom:',
    '    div_geom(a,b)   → witness or quotient+remainder Dict',
    '    ratio_geom(a,b) → RatioRule',
    '    sqrt_geom(n)    → exact witness or bounds+rule Dict',
    '',
    '  resonance_geom:',
    '    sequence_packet(seq) → period/energy/phase Dict',
    '    resonance_din(seq)   → DINPacket',
    '    e8_seed_hint(seq)    → E8 embedding hint Dict',
    '',
    '══════════════════════════════════════════════════════',
    'A17. KEY PRINCIPLES',
    '══════════════════════════════════════════════════════',
    '',
    '  Number = relational web, not digit string.',
    '  Axis = Doctor = rule (d,d,d) = zero tension.',
    '  D_body=0 ↔ on_axis ↔ CLOSED.',
    '  Triangle angle = side ratio, not degree number.',
    '  Doctor connects spaces through relations, not coordinates.',
    '',
    'A18. IF UNSURE',
    '',
    '  Run api().',
    '  When method returns Pt/Pt3 — use .x .y .z, not tuple unpack.',
    '  slice_xy / slice_xz / slice_yz are ATTRIBUTES, not methods.',
    '  angular_tunnel key is "same_dir" not "same_direction".',
    '  e8gen.summary() key is "total_roots" not "root_count".',
    '  Prefer compact dict packets over prose for AI output.',
]
# [8:1] API_LINES_END

# [9:0] OPT_GEOM_LINES_BEGIN
OPT_GEOM_LINES = [
    'PYTHFIELD /opt_geom — OPT_G and Doctor-centered geometry of descent',
    '',
    'OG1. WHAT OPT_G IS',
    '  OPT_G is the geometry of moving from a distorted or partial state',
    '  toward the nearest stable node where independent invariants close.',
    '  Short rule:',
    '    if exact witness exists → read it.',
    '    else → descend geometrically toward the nearest stable node,',
    '    then let Doctor certify whether the landing is truly closed.',
    '',
    'OG2. WHY THIS IS NEEDED',
    '  Many objects are not direct addresses but shadows:',
    '    - 3D invariants V/C/S without x,y,z',
    '    - a product cloud with many factor witnesses',
    '    - a resonance packet with support modes but no geometric landing',
    '  The question becomes: which nearby node reduces tension and closes the object?',
    '',
    'OG3. STABLE NODE',
    '  A stable node is a state where independent routes agree enough',
    '  that Doctor calls it CLOSED or at least admissible with explicit residue.',
    '  A false minimum looks cheap locally but breaks the wrong closures.',
    '',
    'OG4. DOCTOR STANDS AT THE CENTER',
    '  OPT_G chooses how to move among roads.',
    '  Doctor decides whether the move really reduced the right tension.',
    '  OPT_G without Doctor → can land in a false minimum.',
    '  Doctor without OPT_G → can diagnose but not guide descent.',
    '',
    'OG5. 2D SOFT DESCENT (VERIFIED)',
    '  Among valid factor witnesses for P, prefer the one nearest the diagonal (smallest |D|).',
    '  Examples:',
    '    P=120  → best (10,12), worst (1,120)',
    '    P=420  → best (20,21), worst (1,420)',
    '  doctor.choose_best_factor(P) returns Pt (access .x .y).',
    '',
    'OG6. 2D TENSION LADDER',
    '  A product web is a ladder away from the diagonal.',
    '  Near-diagonal = low tension. Edge witnesses (1,P) = maximal stretch.',
    '',
    'OG7. 2D FRACTURE SIGNATURES (VERIFIED)',
    '  Different distortions break different route families:',
    '    ()              → CLOSED',
    '    (C2,)           → LOCAL_RECONSTRUCTION_DRIFT',
    '    (C1,C2)         → SUM_OR_DIFF_FRACTURE',
    '    (C1,C3h,C4h)    → PRODUCT_WITNESS_FRACTURE',
    '',
    'OG8. 3D DESCENT BY INVARIANTS',
    '  Given V, C_plan, S_lin — resolve_invariants finds the chamber-consistent triple.',
    '  Example: (30,31,10) → [2,3,5].',
    '  Changing any one invariant destroys recoverability.',
    '',
    'OG9. 3D SOFT TRIPLETS (VERIFIED)',
    '  hyp3(V) returns triples sorted by D_body (most symmetric first).',
    '  doctor.choose_best_triplet(V) returns Pt3 (access .x .y .z).',
    '  Examples:',
    '    V=120 → best (4,5,6), worst (1,1,120)',
    '    V=840 → best (7,10,12)',
    '',
    'OG10. CHAMBER DESCENT',
    '  Think in chamber profile (a, d1, d2) rather than raw coordinates.',
    '  Descent = reducing asymmetry in d1, d2, or D_body.',
    '',
    'OG11. TUNNEL BRIDGE (VERIFIED)',
    '  tunnel(P2d, V3d, phase) lifts a 2D shadow into a 3D witness.',
    '  Example: tunnel(6,30,0) → (1,6,5), both xy_ok and vol_ok.',
    '  Failure: tunnel(7,30,0) → None. This is a real result — the route is not open.',
    '',
    'OG12. SEED AS DESCENT TARGET',
    '  A stable node may be a primitive seed + scale + tag.',
    '  Examples:',
    '    (-35,14,-21) → primitive (2,3,5), scale 7, tag zxy:p5',
    '    (2,3,5)      → primitive itself',
    '  Descend to primitive structure first, then expand scale.',
    '',
    'OG13. RESIDUE IS HONESTY',
    '  If exact witness cannot be reached, keep residue visible:',
    '    quotient + remainder, ratio rule, repeating rule, irrational rule.',
    '  Do not invent certainty.',
    '',
    'OG14. RESONANCE LANDSCAPES',
    '  In sequence space, stable nodes appear as support patterns.',
    '  Doctor reads whether the packet is stable or fractured.',
    '  Examples: multiplicative [2,4,8,...] → OK; flat [5,5,5,...] → ROLLBACK.',
    '',
    'OG15. MERGE POLICIES MATTER',
    '  merge() averages channels. merge_max() preserves worst channel.',
    '  The same mixed packet can be OK under average but WARN under worst-case.',
    '',
    'OG16. FINGERPRINT DESCENT',
    '  Some objects are better classified by distribution than by one witness.',
    '  classify_zero_divisor_profile matches 8-sign vs 16-sign families.',
    '',
    'OG17. GRAPH DESCENT VIA PLAFAL',
    '  tension_with() reads conflict density on shared structure.',
    '  plafal_graph_summary shows cross-kind vs within-kind tension.',
    '',
    'OG18. OPT_G IS NOT',
    '  Not Newton-Raphson, not brute force, not black-box optimization.',
    '  It is geometry-aware descent with closure-aware verification.',
    '',
    'OG19. PRACTICAL RULE FOR AI',
    '  When exact witness is absent, ask:',
    '    what is the nearest stable node?',
    '    which channels close there?',
    '    what residue remains?',
    '    is this a valid bridge or a false minimum?',
]
# [9:1] OPT_GEOM_LINES_END

# [10:0] DOCTOR_LINES_BEGIN
DOCTOR_LINES = [
    'PYTHFIELD /doctor — health, closure, routing, projection honesty',
    '',
    'D1. WHAT DOCTOR IS',
    '  Doctor is the geometry-of-relations health layer.',
    '  It measures closure, support loss, ambiguity, drift,',
    '  projection loss, modality conflict, and stress.',
    '  It issues verdicts. It does not compute — it reads routes.',
    '',
    'D2. CORE HEALTH VECTOR',
    '  HealthVector fields:',
    '    .closure          — fraction of failed routes',
    '    .support_loss     — 1/(1+support)',
    '    .ambiguity        — uncertainty from multiple routes',
    '    .drift            — instability under small changes',
    '    .projection_loss  — information loss in projection',
    '    .modality_conflict— conflict between different spaces',
    '    .stress           — weighted sum of all above',
    '  0.0 means perfectly closed/clean on that channel.',
    '',
    'D3. CURRENT CORE FUNCTIONS',
    '  doctor.from_routes(agreements, total_routes) → HealthVector',
    '  doctor.from_closures({"C1":True,...}) → HealthVector',
    '  doctor.from_retrieval(support, ambiguity, coverage, drift) → HealthVector',
    '  doctor.merge(*hvs)       → HealthVector (average)',
    '  doctor.merge_max(*hvs)   → HealthVector (worst channel)',
    '  doctor.judge(hv, context="") → DoctorVerdict',
    '  doctor.judge_ok()        → DoctorVerdict (OK shortcut)',
    '',
    'D4. 2D CLOSURES',
    '  doctor.pt2d(x,y) checks 5 channels:',
    '    C1: P = (S² - D²)//4',
    '    C2: sd(S,D) reconstructs the point',
    '    C3h: web(P).at(x) returns the point',
    '    C4h: web(P).at(y) returns the mirror point',
    '    C5: canon/tag roundtrip returns the original address',
    '  Fracture signatures:',
    '    ()            → CLOSED',
    '    (C2,)         → LOCAL_RECONSTRUCTION_DRIFT',
    '    (C1,C2)       → SUM_OR_DIFF_FRACTURE',
    '    (C1,C3h,C4h)  → PRODUCT_WITNESS_FRACTURE',
    '',
    'D5. 3D CLOSURES (HOLOGRAPHIC)',
    '  doctor.pt3(x,y,z) checks 3 holographic channels:',
    '    Hxy: slice_z.P * |z| == |V|',
    '    Hxz: slice_y.P * |y| == |V|',
    '    Hyz: slice_x.P * |x| == |V|',
    '',
    'D6. TERNARY CLOSURES (AXIS DOCTOR)',
    '  doctor.pt3_field3(x,y,z) = Axis.doctor_full(x,y,z)',
    '  Checks 6 channels on the ternary address stack:',
    '    C1_hxy, C2_hxz, C3_hyz — holographic witnesses',
    '    C4_axis — every stack level is (d,d,d)',
    '    C5_phase — phase roundtrip exact',
    '    C6_dbody — D_body=0 ↔ on_axis',
    '  Signature: CLOSED (tension=0) or FRACTURED:["C4_axis"] (tension=1)',
    '',
    'D7. BEST WITNESS (OPT_G-LIKE)',
    '  doctor.choose_best_factor(P) → Pt (.x .y, NOT tuple)',
    '    Returns factor pair nearest the diagonal (smallest |D|).',
    '  doctor.choose_best_triplet(V) → Pt3 (.x .y .z)',
    '    Returns most symmetric triple (smallest D_body).',
    '',
    'D8. TUNNEL DOCTOR',
    '  doctor.tunnel_packet(P2d, V3d, phase) → Dict',
    '    Checks: tunnel_exists, xy_ok, vol_ok.',
    '    Tunnel is witness-lift, not historical inverse.',
    '',
    'D9. SEED / RESONANCE DOCTOR',
    '  doctor.seed_packet_health(x,y,z) → Dict',
    '    Checks primitive/scale/tag roundtrip.',
    '  doctor.resonance_packet(seq) → Dict',
    '    Wraps sequence_packet + verdict.',
    '',
    'D10. ANGLE CONSTANTS AS RELATIONS',
    '  doctor.angle_constant(degrees) → Dict',
    '    Exact cos/sin as ratios (num,den) for:',
    '    0°, 30°, 45°, 60°, 90°, 120°, 135°, 150°, 180°.',
    '    For all other angles: markup only, no exact ratio.',
    '    cos(60°)=(1,2), cos(90°)=(0,1). No float. No degrees inside.',
    '',
    'D11. PYTHAGOREAN ANGLE',
    '  doctor.pythagorean_angle(a,b) → Dict',
    '    cos² = a²/(a²+b²), sin² = b²/(a²+b²) — exact fractions.',
    '',
    'D12. TRIANGLE GEOMETRY (EXACT, NO FLOATS)',
    '  doctor.triangle_from_sides(a,b,c) → Dict',
    '    cos_num, cos_den — exact integers.',
    '    shape: equilateral|right|isoceles|obtuse|acute_scalene.',
    '  doctor.equilateral_from_side(s) → Dict',
    '    cos(60°)=(1,2), sin_sq=(3,4), on_axis=True.',
    '  doctor.triangle_closure(a,b,c) → Dict',
    '    altitudes, medians, bisectors, altitude_feet — exact fractions.',
    '',
    'D13. METRIC MARKUP (ADDRESS, NOT COMPUTATION)',
    '  doctor.metric_markup(value, bits, low, high) → Dict',
    '    Divides [low,high] into 2^bits cells.',
    '    Returns cell_index, bit_address, cell_bounds.',
    '    Scale-invariant: same value gives same cell_index',
    '    regardless of range, because it is a position, not a computation.',
    '  doctor.metric_markup_ternary(value, depth, low, high) → Dict',
    '    Divides into 3^depth cells, returns trit_address.',
    '',
    'D14. ANGULAR TUNNEL',
    '  doctor.angular_tunnel(p1, p2, target_cos_sq=(num,den)) → Dict',
    '    Checks angle relationship between two vectors.',
    '    target_cos_sq must be a tuple (num,den), not a float.',
    '    Returns: right_angle, same_dir, valid_cos, tension, verdict.',
    '',
    'D15. FINGERPRINT HELPERS',
    '  doctor.fingerprint_counter(items) → Dict',
    '  doctor.fingerprint_compare(a,b) → Dict',
    '  doctor.classify_zero_divisor_profile(profile) → Dict',
    '    Matches 8-sign or 16-sign family.',
    '  doctor.zero_divisor_family(labels) → Dict',
    '',
    'D16. PLAFAL AS DOCTOR LAYER',
    '  doctor.plafal_tension(P,Q) → Dict',
    '    Conflict density on shared vertices/edges.',
    '  doctor.plafal_graph_summary(plafals, kinds) → Dict',
    '    Global tension topology across many graphs.',
    '',
    'D17. QUARANTINE / RELEASE',
    '  doctor.quarantine(key, payload, verdict) — store with verdict.',
    '  doctor.release(key) — remove.',
    '  doctor.get_quarantine(key) — retrieve.',
    '',
    'D18. PPH PROTOCOL',
    '  doctor.pph_report(binary_approx, residue, essence, verdict)',
    '  doctor.projection_loss_numeric(original, reconstructed)',
    '  Keep residue visible when projecting richer objects into',
    '  poorer surfaces.',
    '',
    'D19. MERGE MODES',
    '  merge() averages channels. merge_max() preserves worst channel.',
    '  Same packet set can be OK under average, WARN under worst-case.',
    '',
    'D20. DOCTOR AND OPT_G',
    '  OPT_G chooses how to move among roads.',
    '  Doctor decides whether the move really reduced the right tension.',
    '  Together they form the central bridge geometry.',
    '',
    'D21. HISTORICAL NOTE',
    '  Earlier concepts of Doctor included a universal tension constant',
    '  (3.042336), a global find_path oracle, and canonical angles',
    '  (35°, 70.1°, 105°, 140°). These are not implemented in current code.',
    '  Current Doctor is a closure-health layer with exact ratio geometry.',
    '  Keep historical and current meanings separate.',
    '',
    'D22. FINAL RULE',
    '  If a route closes → let Doctor certify it.',
    '  If routes disagree → let Doctor show which channels broke.',
    '  If no direct witness exists → descend toward a softer stable node,',
    '  then let Doctor decide whether it is trustworthy or merely convenient.',
    '  Doctor does not compute. Doctor reads routes.',
]
# [10:1] DOCTOR_LINES_END

HELP = "\n".join(HELP_LINES)
AXIOMS = "\n".join(AXIOMS_LINES)
GEOM_HELP = "\n".join(GEOM_LINES)
GPT_HELP = "\n".join(GPT_LINES)
ACADEMY_HELP = "\n".join(ACADEMY_LINES)
PYTH_HELP = "\n".join(PYTH_LINES)
MACROS_HELP = "\n".join(MACROS_LINES)
API_HELP = "\n".join(API_LINES)
OPT_GEOM_HELP = "\n".join(OPT_GEOM_LINES)
DOCTOR_HELP = "\n".join(DOCTOR_LINES)

def help():
    print(HELP)
    return HELP

def help_axioms():
    print(AXIOMS)
    return AXIOMS

def help_geom():
    print(GEOM_HELP)
    return GEOM_HELP

def help_gpt():
    print(GPT_HELP)
    return GPT_HELP

def help_academy():
    print(ACADEMY_HELP)
    return ACADEMY_HELP

def help_pyth():
    print(PYTH_HELP)
    return PYTH_HELP

def help_macros():
    print(MACROS_HELP)
    return MACROS_HELP

def help_api():
    print(API_HELP)
    return API_HELP

def help_opt_geom():
    print(OPT_GEOM_HELP)
    return OPT_GEOM_HELP

def help_doctor():
    print(DOCTOR_HELP)
    return DOCTOR_HELP

def slash(cmd: str):
    c = str(cmd).strip()
    if c == '/help': return help()
    if c == '/axioms': return help_axioms()
    if c == '/geom': return help_geom()
    if c == '/gpt': return help_gpt()
    if c == '/academy': return help_academy()
    if c == '/pyth': return help_pyth()
    if c == '/macros': return help_macros()
    if c == '/api': return help_api()
    if c == "/opt_geom":
        return help_opt_geom()
    if c == "/doctor":
        return help_doctor()
    raise ValueError('unknown cmd. try: /help /axioms /geom /gpt /academy /pyth /macros /api')

if __name__ == "__main__":
    print("helpdoc.py loaded. use slash('/help')")

""" Логика построения e8 print("=== E8_248 LESSON: VERIFIED INVARIANTS ===")"""
print("Integer-only. Every claim checked. No assumptions.\n")
